<?php
/**
 *
 * @category    Jworks
 * @package     Jworks_UrlRewriteImport
 * @author Jitheesh V O <jitheeshvo@gmail.com>
 * @copyright Copyright (c) 2017 Jworks Digital ()
 */

// @codingStandardsIgnoreFile

?>
<div class="import-export-tax-rewrites">
    <?php if (!$block->getIsReadonly()): ?>
    <div class="import-tax-rewrites">
        <?php if ($block->getUseContainer()): ?>
        <form id="import-form" class="admin__fieldset" action="<?php /* @escapeNotVerified */ echo $block->getUrl('urlrewrite/import/importPost') ?>" method="post" enctype="multipart/form-data">
        <?php endif; ?>
            <?php echo $block->getBlockHtml('formkey')?>
            <div class="fieldset admin__field">
                <label for="import_rewrites_file" class="admin__field-label"><span><?php /* @escapeNotVerified */ echo __('Import URL rewrites') ?></span></label>
                <div class="admin__field-control">
                    <input type="file" id="import_rewrites_file" name="import_rewrites_file" class="input-file required-entry"/>
                    <?php echo $block->getButtonHtml(__('Import URL rewrites'), '', 'import-submit') ?>
                </div>
            </div>
        <?php if ($block->getUseContainer()): ?>
        </form>
        <?php endif; ?>
        <script>
require(['jquery', "mage/mage", "loadingPopup"], function(jQuery){

    jQuery('#import-form').mage('form').mage('validation');
    (function ($) {
        $('.import-submit').click(function(){
            if($(':input[name="import_rewrites_file"]').val()) {
                $('body').loadingPopup({
                    timeout: false
                });

                $(this.form).submit();
            }
        });
    })(jQuery);

});
</script>
    </div>
    <?php endif; ?>
</div>
